### ISSUE TITLE
High CPU usage and constant RAM consumption after resume from standby

### ISSUE THREAD

**Issue by Simon-Dainty** [xenolightning/AudioSwitcher_v1#682] opened 2015-03-24 11:18 UTC
Hey, AudioSwitcher, upon resume-from-standby (of more than a few minutes), kicks into consistently high CPU usage and starts gobbling up RAM.  I've not been able to look into the issue more fully at the moment, but it seems confined to resume-from-standby only.

Regards,

Simon.

**Comment by xenolightning** [comment] 2015-03-25 04:24
How are you entering stand by?

What operating system?

**Comment by Simon-Dainty** [comment] 2015-03-25 15:20
Stand by is via the power button and I'm running Windows 8.1.
Incidentally, the issue doesn't present itself if the machine is in standby
for only a few minutes (which is strange in itself).  And for what it's
worth, I'm using both onboard audio (a Z97P motherboard) and a Soundblaster
Audigy 2 ZS.

I'll try delve a little deeper when I get the opportunity.

Regards,

Simon.

**Comment by xenolightning** [comment] 2015-03-25 21:21
Seems very strange. I'll give it a go and see if I can reproduce it on my laptop too.

**Comment by Simon-Dainty** [comment] 2015-03-26 01:01
Very strange.  It seems somewhat intermittent now, but I was getting the
issue regularly a day or so ago.  If I can find the time I'll build a debug
version from your sources and capture it in Visual Studio if/when it
happens again...

Regards,

Simon.

**Comment by xenolightning** [comment] 2015-03-27 02:37
Yeah that'd be good.

I couldn't reproduce it on my laptop, I'm going to mark it as intermittent and wont fix for now.

**Closed by xenolightning** 2015-03-27 02:37 UTC
Labels: intermittent, wontfix
