### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kav2k** [xenolightning/AudioSwitcher_v1#1900] opened 2016-01-30 11:33 UTC
My Audioswitcher 1.6.10.113 is exibiting a severe memory leak.

When I noticed, the memory used by the process grew to 12+ Gb and my system started swapping.

The leak is reproducible, but I don't know what triggers it yet. I have a hunch it may have to do with sleep/resume.

I would be happy to help with debugging, but I may need a bit of guidance (not a C# dev, unfamiliar with Visual Studio). For now, I built a debug version of the release and will be running it with a debugger attached to see if I manage to extract any useful info from there.

**Comment by xenolightning** [comment] 2016-01-30 11:53
Eeesh that's not good!

Sounds like you are on the right track, if you do manage to get reproducible steps fire them my way and I should be able to track it down pretty quickly.

Its most likely to be in the Audio Api, which you can build from source in the api repo up on GitHub.

**Comment by kav2k** [comment] 2016-01-30 11:55
I have a dump from a release version exhibiting the problem, but I'm not sure how useful that would be. I can upload it nevertheless.

**Comment by kav2k** [comment] 2016-01-30 11:58
Here it is nevertheless, a ["minidump + heap"](https://mega.nz/#!pRpnXDYJ!33FQ_VHZtSvMdUA9YZZgVZt8WKJSOrXqS_kxTcDKbP4)

**Comment by xenolightning** [comment] 2016-02-01 11:04
Ok! So after waiting for what seemed like an age I managed to load the entire dump and heap, and get the object reference information from it.

There's certainly something wrong, and it looks to be in the async task scheduling. 

Did you have any luck finding some easy reproducible steps? I'm not sure what is getting the application into this state yet.

![2016-02-01_23-58-54](https://cloud.githubusercontent.com/assets/6000196/12715603/0cd3f4e4-c940-11e5-90d3-3ecb38e833a9.png)

**Comment by kav2k** [comment] 2016-02-01 11:08
Not yet, unfortunately. I have been running the debug version since and have not noticed it happening again. Before, I observed it twice, so it's not one freak accident.

I'll notify you if I have this reproduced in the debug build.

**Comment by xenolightning** [comment] 2016-02-01 20:41
I have no doubt there's an issue in there. I did find a weird compounding issue with system events in the Api, which caused a large slew of tasks to be created faster than the cpu could execute them. It effectively allowed for an infinite list to be created in memory.

It's been fixed in master for the Api, so it may also fix this.

**Comment by estorial** [comment] 2016-02-01 21:53
Hello, I can confirm that the exact same thing happened to me as well. On windows 10 I heard my swap disc start up and checked memory usage. I found the task Audio Switcher using 9.4 GB of ram.

**Comment by xenolightning** [comment] 2016-02-01 22:27
Thanks for that. Any idea what may have caused it?

I'm actively running Audio Switcher on 3 PC's trying to get it happen, but I haven't seen it yet.

While trying to find this bug, I found another one too xD

**Comment by xenolightning** [comment] 2016-02-01 23:25
Actually I may have found the culprit. There seems to be a deadlock when a device is disabled, and the audio sessions are attempted to be cleaned up.

The deadlock is on the low level device implementation, which more or less means anything that happens in the system after the deadlock creates a huge list of background tasks that never get executed.

I'll attach a debug build in here for testing later tonight.

**Comment by xenolightning** [comment] 2016-02-03 09:54
Some early debug builds which include some attempted fixes for this memory leak. If anyone could give it a test, that would be great.

You can try the packed or unpacked version. Not a lot of difference, the packed version is closer to a "production" release.

[Debug_Packed.zip](https://github.com/xenolightning/AudioSwitcher_v1/files/115415/Debug_Packed.zip)
[Debug_Unpacked.zip](https://github.com/xenolightning/AudioSwitcher_v1/files/115416/Debug_Unpacked.zip)

**Comment by xenolightning** [comment] 2016-02-03 10:04
Scenarios I've tested (with Audio Switcher is running):
- Uninstalling & re-installing an audio device (my microphone)
- Putting the computer to sleep then waking
- Disabling/enabling a device in control panel
- Changing properties & speaker configs
- Reinstalling Video Card drivers

**Comment by kav2k** [comment] 2016-02-03 22:02
Reinstalling video card drivers - you may be onto something here, I think my case can be related.

I still can't reproduce it though on the debug build of 1.6.10.113

**Comment by xenolightning** [comment] 2016-02-03 22:29
Yeah drivers installation can do funky things to device states. It might be a good exploration point.

I really do think this is a fairly uncommon leak at the best of times. I've been running Audio Switcher 1.6.10 on 3 PC's, and have yet to reproduce it once. 

There might be a release in the near future to fix a few other small issues.

I might leave this open to track it, until we have no reports from any current build.

**Comment by kav2k** [comment] 2016-02-05 08:11
So, I caught it on the debug 1.6.10.113! It's live now in my system.

I still have no idea what triggers it. I can tell you that one of my sound devices is in an abnormal state - I cannot change the audio level to anything but 100. I noticed that first, and checked the AudioSwitcher. And yes, it was at 300 MB memory and growing steady.

Here's what a 40 second heap difference looks like:

![image](https://cloud.githubusercontent.com/assets/1549691/12841013/5ec0c0ac-cbe8-11e5-92ad-f68103fc3e93.png)

However, nothing really new here. Can I inspect anything else to help?

**Comment by xenolightning** [comment] 2016-02-05 08:18
Nice!

It certainly looks like the deadlock. 

There's a background task scheduler, which runs those "Task" and "ContinuationTaskFromTask" objects, and slowly churns through them. If for whatever reason one of those tasks doesn't ever finish executing then it will create a backlog that will never get executed.

There might be a way to confirm what is holding up the execution. I'll have a quick look and get back to you in a sec

**Comment by xenolightning** [comment] 2016-02-05 08:33
Ok, you might be able to dig around at it in the Threads window.

Just dump the contents in here, I should be able to find the culprit at a glance.

![2016-02-05_21-31-44](https://cloud.githubusercontent.com/assets/6000196/12841331/f57d47d8-cc4f-11e5-9bbf-72cc7989f860.png)

**Comment by kav2k** [comment] 2016-02-05 08:35
Here you go, does that help?

![image](https://cloud.githubusercontent.com/assets/1549691/12841397/c502f15c-cbeb-11e5-8b54-dcaf0220a9ea.png)

**Comment by xenolightning** [comment] 2016-02-05 08:40
Perfect! It's most likely in thread 23. That method call this class here:

https://github.com/xenolightning/AudioSwitcher/blob/master/AudioSwitcher.AudioApi.CoreAudio/Internal/AudioEndpointVolume.cs

Because COM is stupid, it has to be executed on the same thread. So that call to volume, and a bunch of other low level calls are all scheduled on that thread.

If that thread is blocking for whatever reason, nothing will be executed.

It seems that `IAudioEndpointVolume.GetMasterVolumeLevelScalar` is not returning, _at all_. Which signals something really bad is happening even lower than Audio Switcher. And also ties into you not being able to control volume properly.

**Comment by kav2k** [comment] 2016-02-05 08:44
I tried replugging the device in question (which happens to be SB X-Fi Go! Pro) and that did not help. Strange.

**Comment by xenolightning** [comment] 2016-02-05 08:45
Are you able to change the volume to levels other than 100 now?

**Comment by kav2k** [comment] 2016-02-05 08:45
No, that's the thing. After re-plugging the physical device, I still can't. And I can change volume on my other audio device, JBL Pebbles.

**Comment by xenolightning** [comment] 2016-02-05 08:49
You can kill Audio Switcher now. I think we have enough information around what's causing it. And see if then you are able to change volume.

I might create an enhancement to cancel tasks that seem to be running too long, not sure on whether it will fix the issue, but it may stop Audio Switcher from leaking terribly.

**Comment by kav2k** [comment] 2016-02-05 08:51
Nope, still doesn't help. I know it will go away if I restart, which is what I'll probably do.

Thanks for continued support!

**Comment by xenolightning** [comment] 2016-02-05 08:54
No prob. I'd like to "fix" Audio Switcher, so it doesn't leak in these situation, even if the system is bugged.

You could try new drivers for the X-Fi if they're available.

**Comment by kav2k** [comment] 2016-02-05 08:58
Still would be great to hear from @estorial if he could reproduce it and if there are similar symptoms.

**Comment by xenolightning** [comment] 2016-02-16 10:08
A more stable build preview of the next version, 1.7.0.116-rc1.

Note it now uses .net 4.5.2, so you'll need to install it before running. However, it's default in Windows 8+

Will aim to push a full release sometime later this week.

[AudioSwitcher.zip](https://github.com/xenolightning/AudioSwitcher_v1/files/132235/AudioSwitcher.zip)

**Comment by kav2k** [comment] 2016-02-16 10:13
FWIW, I encountered the leak again (being on the release version) while there was no problem with volume or any other easily-detectable problem with sound system. Sadly, had no time to inspect what was hanging this time.

**Comment by xenolightning** [comment] 2016-02-16 10:25
Would be nice to find out if there's something else causing it. It could well have been the audio session issue I addressed (somewhere above).

It shouldn't ever happen again though, there's a bunch of checks that prevent the spamming of tasks even when something blocks. 

Should be quite a stable release, there has been a lot of improvements under the hood.

**Comment by thedewi** [comment] 2016-02-20 07:00
Just for another data point: this has happened to me twice on 1.6.10.113. Previous versions tended to hang a lot as well, which I sometimes suspect could be:
(1) two audio devices regularly appear/disappear when turned on and off, one USB one and one on Nvidia HDMI.
(2) I switch between logged-in users regularly (Win7 x64).
I will see how the preview goes.

**Comment by krakentoa** [comment] 2016-02-27 11:00
It happened on my system too. I'm using the 1.7 rc1 posted here now.

**Comment by xenolightning** [comment] 2016-02-29 00:31
@krakentoa  @thedewi Thanks for the reports.

Let me know if you run into the issue on the preview build :+1:

**Comment by AreFinstad** [comment] 2016-03-01 14:49
just gonna note that i have had no leak since i started using the preview posted here two weeks ago. 
around 48h and counting and no sign of it.
the official release did have issues within 12 hours as it was using everything i had.

**Comment by xenolightning** [comment] 2016-03-01 21:02
@AreFinstad That's a great bit of info, cheers!

I'm pretty happy that this is fixed and ready to go, I'm making minor adjustments to prep the api for v2, we should see an official release this weekend.

**Comment by karasuhebi** [comment] 2016-03-05 17:15
Just wanted to chime in and say that this is definitely an issue. It's happened to me at least 3 times in 1.6.10.113. I will try out the latest preview build to see if it happens then, although it might be hard to know if it's fixed or not because it doesn't happen all too often.

-Windows 10 Pro x64

**Comment by xenolightning** [comment] 2016-03-08 09:31
Official release out:

https://github.com/xenolightning/AudioSwitcher_v1/releases/tag/1.7.0.117

**Closed by xenolightning** 2016-03-08 09:31 UTC
Labels: audio-api, bug
