### ISSUE TITLE
SetDefaultDevice times out due to invalid device - Catch Error

### ISSUE THREAD

**Issue by Mik3yZ** [xenolightning/AudioSwitcher_v1#2125] opened 2016-03-29 07:29 UTC
`System.TimeoutException: COM operation 'SetDefaultDevice' did not complete in the requested time period.
   at AudioSwitcher.AudioApi.CoreAudio.CoreAudioDevice.SetAsDefault(CancellationToken cancellationToken)
   at FortyOne.AudioSwitcher.AudioSwitcher.Form_Load()`

**Comment by xenolightning** [comment] 2016-03-29 08:48
Most likely caused by the device being in an invalid state when trying to set it as the default.

I assume you have a start up device set.

The error doesn't mean much, it may have still set the default device, but it took longer than expected.

It's on the fix list for the next version.

And for some reason it's not included in 1.7.1, this issue can track it.

**Comment by xenolightning** [comment] 2016-04-08 01:35
Duplicate of #2007

**Closed by xenolightning** 2016-04-08 01:35 UTC
Labels: bug, client

**Comment by ReFruity** [comment] 2017-08-30 22:07
@xenolightning I got similar error when I pressed RMB on AudioSwitcher tray icon and selected headphones.  Before that it had stopped switching to headphonesmy hotkey. Switching to speakers works fine. Earlier I had installed Audio Repeater and played with channeling (channelled headphones mic and line-in in one channel). Maybe this information could help. 

Also I'll post stacktrace here, the report button doesn't seem to work in the report window.
```
System.TimeoutException: COM operation 'SetDefaultDevice' did not complete in the requested time period.
   at AudioSwitcher.AudioApi.CoreAudio.CoreAudioDevice.SetAsDefault(CancellationToken cancellationToken)
   at FortyOne.AudioSwitcher.AudioSwitcher.notifyIconStrip_ItemClicked(Object sender, ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStrip.OnItemClicked(ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnItemClicked(ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStrip.HandleItemClick(ToolStripItem dismissingItem)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by ReFruity** [comment] 2017-08-30 22:08
@xenolightning Oops, restart fixed it so nevermind :D
