### ISSUE TITLE
programm can't deal with custom icons

### ISSUE THREAD

**Issue by TimetravelerDD** [xenolightning/AudioSwitcher_v1#1358] opened 2015-09-19 17:08 UTC
The programm doesn't display custom icons properly.
with "custom" i mean if you select for the device your own ico file in the windows settings dialog

![audio switcher](https://cloud.githubusercontent.com/assets/14355674/9977286/96a539a2-5f01-11e5-800b-99e39645b8bf.png)

**Comment by IvIePhisto** [comment] 2015-09-19 21:31
I vote for a fix, came across this just yesterday as I wanted to use icons more suitable for the taskbar in Windows 10.

**Comment by xenolightning** [comment] 2015-09-26 07:51
This was done by design because it's impossible to make the icons generic unless they are defined in a fixed set.

I may look at changing it in the future, but for the likes of 2.0, it's already possible to create and define your own icons that affect only AudioSwitcher.

Will leave this open for now, and update it if things change.

**Comment by TimetravelerDD** [comment] 2015-10-06 22:01
that is a very nice solution! However if the programm can't re-recognize the devices (see https://github.com/xenolightning/AudioSwitcher_v1/issues/1357) we have the same problem, and the custom icons would be lost every time along with the favorit status, I guess?

**Comment by xenolightning** [comment] 2015-10-07 10:42
Would set it back to the default icon, yeah.

**Comment by xenolightning** [comment] 2015-12-07 20:55
Have re-introduced the ability to detect icon's. 

Will need to write a piece of code to extract the icons, but this will be included in the next release

**Closed** 2015-12-09 09:44 UTC
Labels: client, enhancement
