### ISSUE TITLE
Start when Windows Starts Issue

### ISSUE THREAD

**Issue by dartharnold** [xenolightning/AudioSwitcher_v1#477] opened 2015-02-01 22:42 UTC
If I check the "Start when Windows starts" options the applications will not start.  When I uncheck the option and put a shortcut into the Start Menu Startup folder two copies start.

**Comment by xenolightning** [comment] 2015-02-03 22:45
Audio Switcher requires some permissions to start with Windows.

It's uses a more robust way to set the application for startup than the Startup Folder, but sometimes this isn't allowed as a normal user.

I don't know under what circumstances that this functionality isn't allowed, so can't resolve the issue.

I would advise using the Startup Folder, and disabling the settings to start with Windows.

**Comment by dartharnold** [comment] 2015-02-04 00:39
I tried that and it would run two instances.  I found if I delay start for about 20 seconds it starts fine.

Jeffrey Arnold

**Comment by xenolightning** [comment] 2015-02-04 00:57
I'll see what I can do to reproduce this by using the startup folder.

It's likely that there will be no fix for this, as it's intended behaviour to launch multiple instances of Audio Switcher.

**Comment by andykamezou** [comment] 2015-02-04 04:46
I think I know the reason why "Start when Windows starts" doesn't work.

When I open my Task Manager->Start-up tab (Windows 8.1), Audio Switcher already there, but when I right click and choose "Properties" or "Open file location", there's nothing happens. So my guess is the location might be incorrectly registered. 

So I checked the registry, it use forward slash (/) instead of backslash (\)
![20150204 124413](https://cloud.githubusercontent.com/assets/6763353/6035303/abadcaf6-ac6b-11e4-9d1d-432f1b922d1f.jpg)

**Comment by xenolightning** [comment] 2015-02-04 04:57
Interesting!

I'll have a look at why it's doing that.

Thanks.,

**Comment by xenolightning** [comment] 2015-02-04 05:03
@andykamezou  Looks like there's a quirk in the .NET libraries which cause directories with a # in the name to reverse the slashes.

There's a way to fix it, and I'll fix it for 1.6.3.2

**Comment by andykamezou** [comment] 2015-02-04 05:12
Oooh. I can confirm that. Tried moving it to a dir without # and the slash appears correctly.

I wonder though if it's the same thing causing @dartharnold start-up issue~

**Comment by dartharnold** [comment] 2015-02-05 03:03
I checked the registry and it looks good.

[image: Inline image 1]

I have tried the startup folder and when it is there two instances are
started.

My current work around is to use the program Starup Delayer 3.0 to start
AudioSwitcher with a 30 second delay on start.

**Comment by andykamezou** [comment] 2015-02-21 12:35
There's still some minor issue with the path with # . It's easy to reproduce.

1. After enabled "Start when Windows starts", the path correctly registered. "D:\#portableApps\AudioSwitcher\AudioSwitcher.exe"

2. Exit the app, relaunch and see the registry changed to the wrong slash "D:\#portableApps/AudioSwitcher/AudioSwitcher.exe"

The wrong slash only registered when the app relaunched after exit/reboot.

I think you forgot to update some line in AudioSwitcher.cs?
https://github.com/xenolightning/AudioSwitcher_v1/blob/master/FortyOne.AudioSwitcher/AudioSwitcher.cs#L633
```
if (Program.Settings.AutoStartWithWindows){
    if (runKey != null)
    runKey.SetValue("AudioSwitcher", "\"" + Application.ExecutablePath + "\"");
}
```

**Comment by xenolightning** [comment] 2015-02-21 22:35
That should be the change that fixes it.

I'll have another look at it

**Comment by xenolightning** [comment] 2015-02-24 02:21
@andykamezou Doh! You are correct.

That's a hangover from some older code.

I'll update it tonight :)

**Comment by xenolightning** [comment] 2015-03-01 23:42
Encompassed into 1.6.4.0, which is ready for packaging, along with a slew of other changes.

Hence the version increase

**Closed** 2015-03-03 11:15 UTC
Labels: bug, client
