### ISSUE TITLE
Hotkeys Disappearing Then Not Being Able to be Reused

### ISSUE THREAD

**Issue by evolucid** [xenolightning/AudioSwitcher_v1#2197] opened 2019-08-10 23:43 UTC
Audioswitcher 1.8.0.142

Windows 10

Sometimes hotkeys stop working and when checked they are not in the list on the Hotkeys tab anymore.

That in itself wouldn't be so bad if I could just reinput the hotkey.  However, Audio Switcher won't let me.  It says that the hotkey is still in use even though it doesn't work and isn't in the list.

So I have to clear ALL hotkeys and set up all of them again just to reinput that one.

**Comment by xenolightning** [comment] 2019-08-11 20:03
Duplicate of https://github.com/xenolightning/AudioSwitcher_v1/issues/2188 - You can use a setting to display unknown devices in hotkeys

**Closed as completed by xenolightning** 2019-08-11 20:03 UTC
Labels: duplicate
